name = "NadGreg"
author = "Nadwey"
version = "1.0.0-alpha.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8825aaa1ce8e7425b1556cb6b66a8d7f695eb93d7e5d51090265311a83bb9923"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.76"

[options]
acceptable-game-versions = ["1.21"]
