name = "NadGreg"
author = "Nadwey"
version = "1.0.0-alpha.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "392e808a92bdcaed99c398cfb897a7f18669a2589249e0cf1883d7c80243e151"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.76"

[options]
acceptable-game-versions = ["1.21"]
