name = "NadGreg"
author = "ursamina & Nadwey"
version = "1.0.0-alpha.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1518bb4b1ab1ace651b89cd847d251cb212473f03cc2771c098df3db950f79f"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
