name = "NadGreg"
author = "Nadwey"
version = "1.0.0-alpha.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3be3ca48135a1df8badfe2671f1d1ba5b233d75c0f834f855a17845b41647f53"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"

[options]
acceptable-game-versions = ["1.21"]
