name = "NadGreg"
author = "ursamina & Nadwey"
version = "1.0.0-alpha.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c889f335f68271926b83fb3113c2a238627325da85139667dcdfd96b577d40d"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
