name = "NadGreg"
author = "Nadwey"
version = "1.0.0-alpha.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f70893eeec309bfb5b594e6323a486f85e6752e3706f0962d08cc314050e84c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"

[options]
acceptable-game-versions = ["1.21"]
