name: build-modpack

on: [push, workflow_dispatch]

jobs:
  build-pack:
    name: Use packwiz to build the curseforge pack
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with: 
          go-version: 'stable'
      
      - name: Install Packwiz
        run: |
          go install github.com/packwiz/packwiz@latest

      - name: Build pack
        run: packwiz curseforge export
      
      - name: Upload pack to actions
        uses: actions/upload-artifact@v4
        with:
          path: NadGreg-*.zip